# docker-compose.yml
services:

  postgre:
    container_name: postgre
    build:
      context: ./postgre
      dockerfile: Dockerfile
      args:
        PG_MAJOR: ${PG_MAJOR}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgre-data:/var/lib/postgresql/data
    networks:
      - shared-network
    restart: always

  minio:
    container_name: minio
    image: minio/minio:latest
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
      - MINIO_SERVER_URL=http://minio:${MINIO_PORT}
    command: server --address :${MINIO_PORT} --console-address :${MINIO_CONSOLE_PORT} /data
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:${MINIO_PORT}/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - minio-data:/data
    networks:
      - shared-network
    restart: always

  minio-client:
    container_name: minio-client
    build:
      context: ./minio-client
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=${MINIO_API_URL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_CLIENT_PORT}:${MINIO_CLIENT_PORT}"
    volumes:
      - ./label-studio/cors.json:/label-studio/cors.json
    networks:
      - shared-network
    depends_on:
      - minio
    restart: always

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - ${NEO4J_WEB_PORT}:${NEO4J_WEB_PORT}
      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - shared-network
    restart: unless-stopped 

  mlflow:
    container_name: mlflow
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MLFLOW_BACKEND_STORE_URI=${MLFLOW_BACKEND_STORE_URI}
      - MLFLOW_ARTIFACT_ROOT=${MLFLOW_ARTIFACT_ROOT}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    depends_on:
      postgre:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./mlflow:/mlflow
    networks:
      - shared-network
    restart: always

  label-studio:
    container_name: label-studio
    build:
      context: ./label-studio
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LABEL_STUDIO_PORT=${LABEL_STUDIO_PORT}
      - LABEL_STUDIO_BUCKET_ENDPOINT_URL=${LABEL_STUDIO_BUCKET_ENDPOINT_URL}
      - LABEL_STUDIO_BUCKET_ACCESS_KEY=${LABEL_STUDIO_BUCKET_ACCESS_KEY}
      - LABEL_STUDIO_BUCKET_SECRET_KEY=${LABEL_STUDIO_BUCKET_SECRET_KEY}
      - LABEL_STUDIO_ROOT_URL=/labelstudio/
      - DJANGO_CSRF_TRUSTED_ORIGINS=${LABEL_STUDIO_HOST}
      - CSRF_COOKIE_SECURE=1
      - POSTGRE_HOST=${POSTGRE_HOST}
      - POSTGRE_PORT=${POSTGRE_PORT}
      - POSTGRE_USER=${POSTGRE_USER}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRE_DB=${POSTGRE_DB}
    ports:
      - "${LABEL_STUDIO_PORT}:${LABEL_STUDIO_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - label-studio-data:/label-studio/data
      - ./label-studio/create_bucket.py:/label-studio/create_bucket.py
      - ./label-studio/cors.json:/label-studio/cors.json
    networks:
      - shared-network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    networks:
      - shared-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - shared-network
    restart: always

  # gliner:
  #   container_name: gliner
  #   image: humansignal/ml-backend:v0
  #   build:
  #     context: ./label-studio-ml-backend/gliner
  #     args:
  #       TEST_ENV: ${TEST_ENV}
  #   env_file:
  #     - .env
  #   environment:
  #     - BASIC_AUTH_USER=${GLINER_BASIC_AUTH_USER}
  #     - BASIC_AUTH_PASS=${GLINER_BASIC_AUTH_PASS}
  #     - LABEL_STUDIO_ML_BACKENDS=${LABEL_STUDIO_ML_BACKENDS}
  #     - LOG_LEVEL=DEBUG
  #     - ANY=PARAMETER
  #     - WORKERS=1
  #     - THREADS=8
  #     - MODEL_DIR=/mlflow/artifacts/models
  #     - LABEL_STUDIO_URL=http://host.docker.internal:${LABEL_STUDIO_PORT}
  #     - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
  #     - HF_HOME=/app/huggingface_cache
  #   ports:
  #     - "${MLBACKEND_PORT}:${MLBACKEND_PORT}"
  #   depends_on:
  #     - label-studio
  #   volumes:
  #     - "./data/server:/data"
  #     - ~/.cache/huggingface:/app/huggingface_cache

  #   networks:
  #     - shared-network

volumes:
  postgre-data:
  minio-data:
  label-studio-data:
  gliner-data:
  mlflow-data:
  neo4j_data:
  neo4j_logs:
  grafana-data:

networks:
  shared-network:
    external: true