services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network
    restart: always

  minio:
    container_name: minio
    image: minio/minio:latest
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_API_URL: ${MINIO_API_URL}
    command: server /data
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
    volumes:
      - minio-data:/data
    networks:
      - shared-network
    restart: always

  minio-client:
    container_name: minio-client
    build:
      context: ./minio-client
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - minio
    networks:
      - shared-network
    restart: always

  mlflow:
    container_name: mlflow
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MLFLOW_BACKEND_STORE_URI=${MLFLOW_BACKEND_STORE_URI}
      - MLFLOW_ARTIFACT_ROOT=${MLFLOW_ARTIFACT_ROOT}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    volumes:
      - ./mlflow:/mlflow
    networks:
      - shared-network
    depends_on:
      - postgres
      - minio
    restart: always

  label-studio:
    container_name: label-studio
    build:
      context: ./label-studio
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_SUPERUSER_USERNAME=${LABEL_STUDIO_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${LABEL_STUDIO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${LABEL_STUDIO_SUPERUSER_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - LABEL_STUDIO_BUCKET_NAME=${LABEL_STUDIO_BUCKET_NAME}
      - LABEL_STUDIO_BUCKET_ENDPOINT_URL=${LABEL_STUDIO_BUCKET_ENDPOINT_URL}
      - LABEL_STUDIO_BUCKET_ACCESS_KEY=${LABEL_STUDIO_BUCKET_ACCESS_KEY}
      - LABEL_STUDIO_BUCKET_SECRET_KEY=${LABEL_STUDIO_BUCKET_SECRET_KEY}
    ports:
      - "${LABEL_STUDIO_PORT}:${LABEL_STUDIO_PORT}"
    volumes:
      - label-studio-data:/label-studio/data
    networks:
      - shared-network
    depends_on:
      - postgres
      - minio
      - mlflow
    restart: always

volumes:
  postgres-data:
  minio-data:
  label-studio-data:
  mlflow-data:

networks:
  shared-network:
    driver: bridge
