{
 "title": "Weavestruct",
 "description": "API",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Query (percentile)",
   "type": "timeseries",
   "description": "emps de traitement des requêtes à 95ème percentile",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(app_process_time_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query (moyenne)",
   "type": "timeseries",
   "description": "Temps moyen traitement des requêtes",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(app_process_time_seconds_sum[5m]) / rate(app_process_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps de latence Neo4j ",
   "type": "timeseries",
   "description": "Temps de latence des requêtes Neo4j (95ème percentile)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(neo4j_request_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total des requêtes Neo4j",
   "type": "timeseries",
   "description": "Success & Failures",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(neo4j_request_count_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(neo4j_request_failures_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps de latence PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(postgres_query_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes PostgreSQL ",
   "type": "timeseries",
   "description": "Success & Failures",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(postgres_query_count_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(postgres_query_failures_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps de réponse HTTP",
   "type": "timeseries",
   "description": "Temps de réponse des requêtes HTTP (95ème percentile)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(metrics_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM GPU",
   "type": "gauge",
   "description": " Affiche l'utilisation actuelle de la mémoire GPU",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Émissions de CO2",
   "type": "timeseries",
   "description": " Approx des émissions de CO2 estimées en grammes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "carbon_emissions_grams", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Utilisation du CPU",
   "type": "gauge",
   "description": "Affiche l'utilisation actuelle du CPU en pourcentage",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}