# label-studio/Dockerfile
FROM heartexlabs/label-studio:latest

# USER root
# COPY entrypoint.sh /entrypoint_label_studio.sh
# RUN chmod +x /entrypoint_label_studio.sh
# USER 1001

# ENTRYPOINT ["/entrypoint_label_studio.sh"]

EXPOSE ${LABEL_STUDIO_PORT}
