global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['app:8001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'label-studio'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['label-studio:8081']

  - job_name: 'mlflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mlflow:5002']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: http
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx:9113']