global:
  scrape_interval: 15s  # Intervalle global pour récupérer les métriques
  evaluation_interval: 15s  # Intervalle pour évaluer les règles d'alerte

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Adresse de l'Alertmanager

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['app:8001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'label-studio'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['label-studio:8081']

  - job_name: 'mlflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mlflow:5002']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: http
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8008']

  - job_name: 'codecarbon'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8002']  # Intégré dans FastAPI sur le port 8002
        labels:
          component: 'codecarbon_tracker'

rule_files:
  # Inclure des fichiers de règles pour les alertes
  - 'alert_rules.yml'
